CREATE TABLE IF NOT EXISTS `website` (
    `website_id` INT PRIMARY KEY AUTO_INCREMENT COMMENT '网站唯一标识',
    `website_name` VARCHAR(255) NOT NULL COMMENT '网站名称',
    `website_url` VARCHAR(255) NOT NULL COMMENT '网站URL',
    `website_desc` VARCHAR(255) COMMENT '网站介绍',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '网站创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '网站更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='网站信息表'; 